version: "3.8"
services:
  prescriptions:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - my_db
  my_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_DATABASE=prescriptions
