openapi: 3.1.0
info:
  title: Prescriptions Service
  description: Prescriptions Service
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Development server

defaults:
  responses:
    '400':
      schema:
        $ref: '#/components/responses/400'
    '401':
      schema:
        $ref: '#/components/responses/401'
    '403':
      schema:
        $ref: '#/components/responses/403'
    '404':
      schema:
        $ref: '#/components/responses/404'
    '500':
      schema:
        $ref: '#/components/responses/500'
    '501':
      schema:
        $ref: '#/components/responses/501'

paths:
  /prescriptions:
    get:
      summary: All prescriptions
      description: All prescriptions from database
      operationId: getAllPrescriptions
      tags:
        - Prescription
      responses:
        '200':
          description: A prescription object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Prescription'
    post:
      summary: Create a prescription
      operationId: createPrescription
      tags:
        - Prescription
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Prescription"
        required: true
      responses:
        '201':
          description: Null response
  /prescriptions/{prescriptionId}:
    get:
      summary: Info for a specific prescription
      operationId: showPrescriptionById
      tags:
        - Prescription
      parameters:
        - name: prescriptionId
          in: path
          required: true
          description: The id of the prescription to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Prescription"

components:
  schemas:
    Prescription:
      description: Prescription model
      type: object
      required:
        - id
        - name
        - user
        - doctor
      properties:
        id:
          description: Prescription id
          type: integer
          readOnly: true
        name:
          description: Prescription name
          type: string
          nullable: false
          minLength: 1
          maxLength: 50
        user:
          description: User that prescription was assigned to
          type: string
        doctor:
          description: Doctor that prescribed prescription
          type: string
        createdAt:
          description: Date when prescription was assigned to user
          type: string
          format: date-time
          example: 2019-10-12T07:20:50.52Z
          readOnly: true
    Doctor:
      description: Doctor which prescribes prescription
      type: object
      properties:
        id:
          description: Doctor id
          type: integer
          readOnly: true
        name:
          description: Doctor name
          type: string
          minLength: 1
          maxLength: 50
        prescriptions:
          description: Prescriptions prescribed by doctor
          type: array
          items:
            $ref: '#/components/schemas/Prescription'
    AppUser:
      description: Application user
      type: object
      properties:
        id:
          description: User id
          type: integer
          readOnly: true
        name:
          description: User name
          type: string
          minLength: 1
          maxLength: 50
        password:
          description: User password
          type: string
        prescriptions:
          description: Prescriptions assigned to user
          type: array
          items:
            $ref: '#/components/schemas/Prescription'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Code of the error message
        message:
          type: string
          description: Error message
  responses:
    400:
      description: The specified resource was not found
    401:
      description: You need to authorize in order to access this resource
    403:
      description: Request forbidden
    404:
      description: Not found
    500:
      description: Internal server error
    501:
      description: Not implemented