openapi: 3.0.3
info:
  title: Prescriptions Service
  description: Prescriptions Service
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Development server

paths:
  /prescriptions:
    get:
      summary: All prescriptions
      description: All prescriptions from database
      operationId: getAllPrescriptions
      tags:
        - Prescription
      responses:
        '200':
          description: A prescription object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Prescription'
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'


    post:
      summary: Create a prescription
      operationId: createPrescription
      tags:
        - Prescription
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Prescription"
        required: true
      responses:
        '201':
          description: Null response
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

  /prescriptions/{prescriptionId}:
    get:
      summary: Info for a specific prescription
      operationId: showPrescriptionById
      tags:
        - Prescription
      parameters:
        - name: prescriptionId
          in: path
          required: true
          description: The id of the prescription to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Prescription"
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

components:
  schemas:
    Prescription:
      description: Prescription model
      type: object
      required:
        - id
        - name
        - user
        - doctor
      properties:
        id:
          description: Prescription id
          type: integer
          readOnly: true
        name:
          description: Prescription name
          type: string
          nullable: false
          minLength: 1
          maxLength: 50
        user:
          description: User that prescription was assigned to
          type: string
        doctor:
          description: Doctor that prescribed prescription
          type: string
        createdAt:
          description: Date when prescription was assigned to user
          type: string
          format: date-time
          example: 2019-10-12T07:20:50.52Z
          readOnly: true
    Doctor:
      description: Doctor which prescribes prescription
      type: object
      properties:
        id:
          description: Doctor id
          type: integer
          readOnly: true
        name:
          description: Doctor name
          type: string
          minLength: 1
          maxLength: 50
        prescriptions:
          description: Prescriptions prescribed by doctor
          type: array
          items:
            $ref: '#/components/schemas/Prescription'
    AppUser:
      description: Application user
      type: object
      properties:
        id:
          description: User id
          type: integer
          readOnly: true
        name:
          description: User name
          type: string
          minLength: 1
          maxLength: 50
        password:
          description: User password
          type: string
        prescriptions:
          description: Prescriptions assigned to user
          type: array
          items:
            $ref: '#/components/schemas/Prescription'
  responses:
    400:
      description: The specified resource was not found
    404:
      description: Not found
    500:
      description: Internal server error
